### ISSUE TITLE
Poor handling for multi-value fields

### ISSUE THREAD

**Issue by Vouzamo** [sdl/dxa-model-service#6] opened 2018-10-12 19:46 UTC
The R2 serialization exposes multi-value field as an object instead of an array when there is only one element populated.

This should always be an array whether there are zero, one, or more elements since the model service is the last point we can reliably check the schema to determine if the field is set to be multi-value or not.

Otherwise it'll be very difficult to consume the JSON without checking each property for being an array / object / literal.

**Comment by rpannekoek** [comment] 2018-10-12 20:05
Note that the Model Service and the R2 Data Model is exposes is **not** a public API; it is the input for tge DXA Semantic Mapping which uses out-of-band Schema information (from `schemas.json`).

The R2 Data Model has intentionally loosely typed content models. This allows a performant conversion from XML to JSON (no need to load & compile Schemas).

Furthermore, for the DXA Semantic Mapping, it doesn’t matter if you are mapping a single-valued field or a multi-valued field which has only a single value.

So: the reported behavior is “by design”.

**Comment by Vouzamo** [comment] 2018-10-12 20:11
What about a use case where semantic mapping is not being used because the R2 model needs to be consumed by a front end application or middleware to pass-through models without having to semantically map everything?

Surely it would be better to take a small performance hit at publish-time versus having this limitation and needing to code around it within the API consumer.

I appreciate that the model service is not considered a public API but the assumption is that it will be eventually so these issues will hopefully help the design decisions be revisited. Otherwise, the likelyhood is that the community will just roll their own OData API for the CIS instead of relying on the R2 data model and DXA.

**Comment by rpannekoek** [comment] 2019-01-31 07:42
The standalone DXA Model Service will not become a public API; instead its functionality gets integrated in the GraphQL Public Content API.  
This is an architecture evolution: the first step has been taken in DXA 2.1 / UDP 11.0 (with the DXA Model Extension for GraphQL Content Service).  In DXA 2.x,  the R2 data model will still be used, but this may change in DXA 3.0.

The purpose of the DXA R2 Data Model remains to be a transport format between CM and DXA Web Applications.   If you want to expose a REST API yourself, you can create a Controller which exposes your Strongly Typed View Models in JSON format.

Closing this issue.

**Closed by rpannekoek** 2019-01-31 07:42 UTC
